CREATE TABLE customers (
    id INTEGER PRIMARY KEY,
    year_birth INTEGER,
    education VARCHAR(50),
    marital_status VARCHAR(50),
    income NUMERIC(12, 2),
    kidhome INTEGER,
    teenhome INTEGER,
    dt_customer DATE,
    recency INTEGER,
    mnt_wines INTEGER,
    mnt_fruits INTEGER,
    mnt_meat_products INTEGER,
    mnt_fish_products INTEGER,
    mnt_sweet_products INTEGER,
    mnt_gold_prods INTEGER,
    num_deals_purchases INTEGER,
    num_web_purchases INTEGER,
    num_catalog_purchases INTEGER,
    num_store_purchases INTEGER,
    num_web_visits_month INTEGER,
    accepted_cmp3 INTEGER,
    accepted_cmp4 INTEGER,
    accepted_cmp5 INTEGER,
    accepted_cmp1 INTEGER,
    accepted_cmp2 INTEGER,
    complain INTEGER,
    response INTEGER
);
